/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jN1rWRpzOvS
 */
import { Label } from "src/components/ui/label";
import { Input } from "src/components/ui/input";
import { Textarea } from "src/components/ui/textarea";
import { Button } from "src/components/ui/button";

export function InquiryForm() {
  return (
    <div className="w-full py-4 font-raleway flex justify-center">
      <div className="container grid max-w-xl md:gap-6">
        <div className="space-y-4">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold">How can we help you today?</h1>
            <p className="text-gray-500 dark:text-gray-400">
              Fill out the form below and we{"'"}ll get back to you as soon as
              possible.
            </p>
          </div>
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="first-name">First name</Label>
                <Input id="first-name" placeholder="Enter your first name" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="last-name">Last name</Label>
                <Input id="last-name" placeholder="Enter your last name" />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" placeholder="Enter your email" type="email" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="inquiry">Message</Label>
              <Textarea
                className="min-h-[100px]"
                id="inquiry"
                placeholder="Enter your message"
              />
            </div>
            <Button>Send inquiry</Button>
          </div>
        </div>
      </div>
    </div>
  );
}
